---
- name: Pull Docker images
  community.docker.docker_image:
    name: "{{ item.image }}"
    source: pull
  loop: "{{ docker_containers }}"

- name: Run Docker containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: started
    restart_policy: "{{ item.restart_policy | default('always') }}"
    ports: "{{ item.ports | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
  loop: "{{ docker_containers }}"

- name: Prune old images and volumes
  ansible.builtin.command: docker system prune -a -f
  changed_when: false
