#SPDX-License-Identifier: MIT-0
---
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
  tags:
    - docker
    - docker_install

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml
  tags:
    - docker
    - docker_config

- name: Import containers tasks
  ansible.builtin.import_tasks: containers.yml
  tags:
    - docker
    - docker_containers
