#SPDX-License-Identifier: MIT-0
---
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
  tags:
    - common
    - common_install

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml
  tags:
    - common
    - common_config

- name: Import service tasks
  ansible.builtin.import_tasks: service.yml
  tags:
    - common
    - common_service
