---
collections:
  # https://galaxy.ansible.com/ui/repo/published/community/general/docs/
  - name: community.general
    version: "11.4.0"
  # https://galaxy.ansible.com/ui/repo/published/ansible/posix/docs/
  - name: ansible.posix
    version: "2.1.0"

roles:
  # https://galaxy.ansible.com/ui/standalone/roles/metno/chrony/documentation/
  - name: metno.chrony
    version: 4.1.0
  # https://galaxy.ansible.com/ui/standalone/roles/robertdebock/fail2ban/documentation/
  - name: robertdebock.fail2ban
    version: 5.0.6
