---
# Common role playbook.
- name: Configure all servers
  hosts: all
  become: true
  serial: "{{ serial_num | default(10) }}"
  tasks:
    - name: Import common role
      ansible.builtin.import_role:
        name: common
      tags: common

    - name: Import chrony role
      ansible.builtin.import_role:
        name: metno.chrony
      tags: chrony

    - name: Import fail2ban role
      ansible.builtin.import_role:
        name: robertdebock.fail2ban
      tags: fail2ban

    - name: Import nftables role
      ansible.builtin.import_role:
        name: ipr-cnrs.nftables
      tags: nftables

    - name: Import docker setup role
      ansible.builtin.import_role:
        name: geerlingguy.docker
      tags: docker_setup

    - name: Import docker role
      ansible.builtin.import_role:
        name: docker
      tags: docker

