---
# Common role playbook.
- name: Configure all servers
  hosts: all
  become: true
  serial: "{{ serial_num | default(10) }}"
  tasks:
    - name: Import common role
      ansible.builtin.import_role:
        name: common
      tags: common

    - name: Import chrony role
      ansible.builtin.import_role:
        name: metno.chrony
      tags: chrony
